{% set name = "wat-inspector" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wat_inspector-{{ version }}.tar.gz
  sha256: 4792406484a8d0fe4451bb1c566fbcdaf6355d7faddd307b29ee2abe7a5aa895

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - python-build
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - wat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/igrek51/wat
  doc_url: https://igrek51.github.io/wat
  summary: Deep inspection of Python objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
