{% set name = "wat-inspector" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wat_inspector-{{ version }}.tar.gz
  sha256: 4262ecdf1fc2ea8e5c35ae65ca1ae18b37d30061936e8bd2f4d6b4020cc05ff3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - python-build
    - wheel
    - pip
  run:
    - python >=3.8

test:
  imports:
    - wat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/igrek51/wat
  doc_url: https://igrek51.github.io/wat
  summary: Deep inspection of Python objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
